### ISSUE TITLE
Pre-commit hook throws error when commit includes a deleted VI

### ISSUE THREAD

**Issue by kunitz** [strainmike/vicommithooks#1]
The issue is here:
https://github.com/strainmike/vicommithooks/blob/5b82192445621397c1bf3ebfb9d436883ad7de3e/vicommithooks/__main__.py#L23

Here is an example of the error:
```
$ git commit -m "testing deleting a vi"
Traceback (most recent call last):
  File "C:\Users\lkunitz\.pyenv\pyenv-win\versions\3.7.9\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\lkunitz\.pyenv\pyenv-win\versions\3.7.9\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\dev\metrology-sw\eng\hooks\.venv\Scripts\vicommithooks.exe\__main__.py", line 7, in <module>
  File "C:\dev\metrology-sw\eng\hooks\.venv\lib\site-packages\vicommithooks\__main__.py", line 95, in main
    options.verbose
  File "C:\dev\metrology-sw\eng\hooks\.venv\lib\site-packages\vicommithooks\__main__.py", line 24, in run_vi_checks
    vi = get_vi(file, parse_diagrams=False, parse_save_record=True)
  File "C:\dev\metrology-sw\eng\hooks\.venv\lib\site-packages\pylabview_helpers\vi.py", line 68, in get_vi
    with open(vi_path, "rb") as rsrc_fh:
FileNotFoundError: [Errno 2] No such file or directory: 'calexec/src/calexecSrc/source/source/Tests/Caraya/Examples/Example2.caraya.vi'

```

I manually modified the script in our workspace with the following check right before the line of code in question and this appeared to fix the issue:
```if os.path.exists(file):```

I tried cloning this workspace and pushing my update to a dev branch, but it doesn't look like this workspace is setup to allow contributions from others.

**Comment by strainmike** [comment]
That's weird that the file doesn't exist since its just walking the directory.  Do any of the files exist or is it using an incorrect relative path or something?

I think on github the main way to contribute to other repos is to fork it, commit your change to your fork, then from your fork an option will appear to open a pull request to the main repo.

**Comment by kunitz** [comment]
That is a good point. The way our commit hook is working right now is that git iterates through the files in the commit and passes each as a single file as an argument to the commit hook. So actually the right place to check for the existence of the file is in the python code the calls the vicommithook script, and skips that script if the file from the commit doesn't exist. Thanks for the quick reply.
